ministryofjustice/wmt-worker

data/00200_offender_manager.js
data/00500_team.js
data/00600_workload_owner.js

Updated seed data creation scripts to include creating multiple managers and assigning to the same team using workload owner link.

WMT-424: offender manager seed data

---

data/00700_workload.js
data/01100_tiers.js

Additional seed data to show functionality for case progress chart

334: Add seed data for tiers and more for workload

---

seed/data/00700_workload.js
seed/data/01100_tiers.js

Adds more comprehnsive test data for tiers

784: Add tier test data

---

seed/views/01000_team_caseload_overview.js

784: Add team caseload overview DB view.

---

seed/views/00902_ldu_case_overview.js
seed/views/00903_region_case_overview.js
seed/views/00904_national_case_overview.js

- Case overview for national, region, ldu updated

Adding missing default contracted hour values to Views

---

seed/data/dev/01200_reductions.js

876: Extend the reductions to include active, scheduled and archived record

---

seed/data/dev/00700_workload.js
seed/data/dev/01100_tiers.js
seed/views/00400_team_caseload_view.js
seed/views/00401_ldu_caseload_view.js
seed/views/00402_region_caseload_view.js
seed/views/00403_national_caseload_view.js

Adds views for caseload by type and updates seed data for total cases in workload table

Feature/wmt 1091/caseload by type

---

database_setup/create-schemas-users.js
database_setup/delete-schemas-users.js
migrations/app/20171002114326_app_user_role_alter_attribute.js
seed/data/dev/01300_users.js

Feature/wmt 751/create wmt user roles role update

---

app/services/data/get-workload-points-configuration.js
migrations/app/20171002131430_app_workload_points_arms_fields.js
package.json
seed/data/dev/00800_workload_points.js
test/helpers/data/app-workload-points-helper.js
test/integration/services/data/test-get-workload-points.js
yarn.lock

Add ARMS fields to workload_points table

Feature/wmt 414/display arms assessments

---

migrations/app/20171001142111_app_users_add_name_attribute.js
seed/data/dev/01300_users.js

1) file that is added: `wmt-worker/migrations/app/20170919114817_app_drop_effective_dates_in_workload_points_calculations.js`
The rest are the merge from master to the branch.

Feature/wmt 1039/store logged in user in workload points

---

seed/data/dev/01000_workload_points_calculations.js

Increase total points in seed data to show that capacity values over 110% are now displayed in red

Create capacity values over 110%

---

app/services/staging-adjustments-mapper.js
app/services/update-adjustment-reduction-status.js
test/helpers/data/staging-adjustments-helper.js

Reverts ministryofjustice/wmt-worker#267

Revert "WMT-34: Using moment() instead of Date() for CMS/GS to fix an issue c…"

---

app/services/workers/etl-worker.js
app/wmt-etl/archive-extract-files.js
app/wmt-etl/run-etl.js

Reverts ministryofjustice/wmt-worker#266

Revert "WMT-12: Fixing an issue where the etl task does not terminate properl…"

---

app/services/staging-adjustments-mapper.js
app/services/update-adjustment-reduction-status.js
test/helpers/data/staging-adjustments-helper.js

Reverts ministryofjustice/wmt-worker#268

Revert "Revert "WMT-34: Using moment() instead of Date() for CMS/GS to fix an issue c…""

---

app/services/workers/etl-worker.js
app/wmt-etl/archive-extract-files.js
app/wmt-etl/run-etl.js

Reverts ministryofjustice/wmt-worker#269

Revert "Revert "WMT-12: Fixing an issue where the etl task does not terminate properl…""

---

app/services/audit-service.js
app/services/aws/sqs/send-sqs-message.js
app/services/data/get-open-reductions-for-court-reporters.js
app/services/data/get-open-reductions.js
app/services/data/insert-workload-owner.js
app/services/insert-workload-owner-and-dependencies.js
app/services/update-adjustment-reduction-status.js
etl-config.js
helm_deploy/wmt-worker/values.yaml
test/helpers/data/app-reductions-helper.js
test/helpers/data/app-workload-helper.js
test/helpers/data/workload-owner-helper.js
test/integration/resources/setup-s3.sh
test/integration/services/data/test-get-open-reductions-for-court-reporters.js
test/integration/services/data/test-get-open-reductions.js
test/integration/services/data/test-insert-workload-owner.js
test/integration/services/test-audit-service.js
test/unit/app/services/test-insert-workload-owner-and-dependencies.js
test/unit/app/services/test-status-updater.js

Reverts ministryofjustice/wmt-worker#316

Reapply WFP-809 audit reduction start and end

---

helm_deploy/values-preprod.yaml

Reverts ministryofjustice/wmt-worker#491

MERGE ON 10TH OCTOBER Revert "Update values-preprod.yaml"

---

helm_deploy/values-preprod.yaml

Reverts ministryofjustice/wmt-worker#527

Revert "WFP-1684: Revert NART extract cron job activation"

---

helm_deploy/values-preprod.yaml

Reverts ministryofjustice/wmt-worker#529

Revert "Revert "WFP-1684: Revert NART extract cron job activation""

---

helm_deploy/values-preprod.yaml

This reverts commit e4741f1b1dc125b576056ad7a56e1bbb49c7e084.

Revert "WFP-1918 enable processing extracts in preprod (#578)"

---

helm_deploy/values-preprod.yaml

Change cron timing load extract

---

helm_deploy/values-preprod.yaml

Reverts ministryofjustice/wmt-worker#706

Revert "nsd cron changes"
